### ISSUE TITLE
please add github as repo url like openosrs

### ISSUE THREAD

**Issue by zakariansudosu** [Arnuh/RuneLiteHijack#7]
hi, please add github as repo url

**Comment by Arnuh** [comment]
This can already be done if you follow the structure.

I've setup an example here https://github.com/Arnuh/RuneLiteHijack-PluginHub which can be used via the url `https://raw.githubusercontent.com/Arnuh/RuneLiteHijack-PluginHub/master/`

I'll also replace the usage of my domain with a github repo as to reduce any risk of using this project.

**Comment by zakariansudosu** [comment]
oke thanks man. that great hehe
